#!/bin/sh
echo "setup libernet into Luci-Services"
echo "Downloading necessary files.."
echo "Please wait...."
#Download iframe
wget -O /usr/lib/lua/luci/controller/libernet.lua \
https://raw.githubusercontent.com/vpnlegasi/libernet/main/View/libernet.lua >/dev/null 2>&1

#make directory libernet
mkdir -p /usr/lib/lua/luci/view/libernet

#Download .lua
wget -O /usr/lib/lua/luci/view/libernet/iframe.htm \
https://raw.githubusercontent.com/vpnlegasi/libernet/main/View/iframe.htm >/dev/null 2>&1

echo "Download complete"
echo "Restart webui"

#restart uhttpd
/etc/init.d/uhttpd restart
echo "Done! Libernet can be access"
echo "Services-Libernet"

rm -f "$0"
